// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIkg5nUAkbtO5M_Tx4yjHQrIaQXDljw3c',
    appId: '1:1057339924007:web:aeeab3bb246ea9cc943802',
    messagingSenderId: '1057339924007',
    projectId: 'agendamedic-c36df',
    authDomain: 'agendamedic-c36df.firebaseapp.com',
    databaseURL: 'https://agendamedic-c36df-default-rtdb.firebaseio.com',
    storageBucket: 'agendamedic-c36df.firebasestorage.app',
    measurementId: 'G-NCZSC08XN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWDAh4EEPzi2oEC_FDifOOTi1k2npckGE',
    appId: '1:1057339924007:android:89d4895cb8bec6a8943802',
    messagingSenderId: '1057339924007',
    projectId: 'agendamedic-c36df',
    databaseURL: 'https://agendamedic-c36df-default-rtdb.firebaseio.com',
    storageBucket: 'agendamedic-c36df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTMD6I9cmyoONodGSOF0hLsIGKt07hVq0',
    appId: '1:1057339924007:ios:1567eb331e118766943802',
    messagingSenderId: '1057339924007',
    projectId: 'agendamedic-c36df',
    databaseURL: 'https://agendamedic-c36df-default-rtdb.firebaseio.com',
    storageBucket: 'agendamedic-c36df.firebasestorage.app',
    iosBundleId: 'com.citamedic.citamedic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTMD6I9cmyoONodGSOF0hLsIGKt07hVq0',
    appId: '1:1057339924007:ios:1567eb331e118766943802',
    messagingSenderId: '1057339924007',
    projectId: 'agendamedic-c36df',
    databaseURL: 'https://agendamedic-c36df-default-rtdb.firebaseio.com',
    storageBucket: 'agendamedic-c36df.firebasestorage.app',
    iosBundleId: 'com.citamedic.citamedic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIkg5nUAkbtO5M_Tx4yjHQrIaQXDljw3c',
    appId: '1:1057339924007:web:5712ea0b347299e2943802',
    messagingSenderId: '1057339924007',
    projectId: 'agendamedic-c36df',
    authDomain: 'agendamedic-c36df.firebaseapp.com',
    databaseURL: 'https://agendamedic-c36df-default-rtdb.firebaseio.com',
    storageBucket: 'agendamedic-c36df.firebasestorage.app',
    measurementId: 'G-EE1J5NY7DX',
  );
}
